export const LANGUAGES = {
  ENGLISH: {
    SELECT_STATUS: "Select Status",
    ACTIVE: "Active",
    DND: "DND",
    OFFLINE: "Offline",
    AWAY: "Away",
    SAVE: "Save",
    USER_STATUS: "User's Status",
    ACCOUNT: "Account",
    VIEWS: "Views",
    STATUS: "Status",
    HOME: "Home",
    ABOUT: "About",
    CONTACT: "Contact",
  },

  HINDI: {
    SELECT_STATUS: "स्थिति चुनें",
    ACTIVE: "सक्रिय",
    DND: "परेशान न करें",
    OFFLINE: "ऑफ़लाइन",
    AWAY: "दूर",
    SAVE: "सेव करें",
    USER_STATUS: "उपयोगकर्ता की स्थिति",
    ACCOUNT: "खाता",
    VIEWS: "दृश्य",
    STATUS: "स्थिति",
    HOME: "Home",
    ABOUT: "About",
    CONTACT: "Contact",
  },
};
